---
  - name: NETDATA | Check if present
    command: test -x /usr/sbin/netdata
    register: netdata_present
    ignore_errors: yes
    changed_when: False
    tags:
      - netdata


  - name: NETDATA | Install package dependencies
    apt: pkg='{{item}}' state=present
    with_items:
     - "zlib1g-dev"
     - "gcc" 
     - "make" 
     - "git" 
     - "autoconf"
     - "autogen" 
     - "automake" 
     - "pkg-config"
     - "uuid-dev"
    when: netdata_present | failed
    become: yes
    tags:
     - netdata 

  - name: NETDATA | Clone for install
    git: repo=https://github.com/firehol/netdata.git dest=/opt/netdata depth="1" dest="/tmp/netdata"
    when: netdata_present | failed
    tags:
      - netdata

  - name: NETDATA | Build and install
    shell: "./netdata-installer.sh --install {{install_dir}} --dont-wait"
    args:
      chdir: /tmp/netdata
    when: netdata_present | failed
    become: yes
    tags:
      - netdata

